config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :beacons
  resources :boards

  get '/beacons/find/:uuid', to: 'beacons#remote', as: 'beacons_find'

  root 'boards#index'

end

app/models/beacon.rb
# Model class for Beacons. Requires UUID specification.
# Board_id can be empty. Which indicates 'Free' beacon.
class Beacon < ActiveRecord::Base
  validates :uuid, :presence => true

  belongs_to :board, class_name: Board
end

app/models/board.rb
# Model class for Boards.
# Requires title.
# When a board ever deleted, all associated posts will also be deleted.
class Board < ActiveRecord::Base
  validates :title, :presence => true

  has_many :beacons, class_name: Beacon
  has_many :posts, class_name: Post, dependent: :destroy
end

app/models/post.rb
# Model class for Posts.
# Requires non-empty content and board_id specification.
class Post < ActiveRecord::Base
  validates :content, :presence => true
  validates :board_id, :presence => true

  belongs_to :board, class_name: Board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  before_action :set_beacon, only: [:show, :edit, :update, :destroy]
  before_action :set_beacon_remote, only: [:remote]

  # GET /beacons
  # GET /beacons.json
  def index
    @beacons = Beacon.all
  end

  # GET /beacons/1
  # GET /beacons/1.json
  def show
  end

  # GET /beacons/find/<uuid>.JSON
  def remote
  end

  # GET /beacons/new
  def new
    @beacon = Beacon.new
  end

  # GET /beacons/1/edit
  def edit
  end

  # POST /beacons
  # POST /beacons.json
  def create
    @beacon = Beacon.new(beacon_params)

    respond_to do |format|
      if @beacon.save
        format.html { redirect_to @beacon, notice: 'Beacon was successfully created.' }
        format.json { render :show, status: :created, location: @beacon.board }
      else
        format.html { render :new }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beacons/1
  # PATCH/PUT /beacons/1.json
  def update
    respond_to do |format|
      if @beacon.update(beacon_params)
        format.html { redirect_to @beacon, notice: 'Beacon was successfully updated.' }
        format.json { render :show, status: :ok, location: @beacon }
      else
        format.html { render :edit }
        format.json { render json: @beacon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beacons/1
  # DELETE /beacons/1.json
  def destroy
    @beacon.destroy
    respond_to do |format|
      format.html { redirect_to beacons_url, notice: 'Beacon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beacon
    # if params[:id].match(/%d/)
    # begin
    @beacon = Beacon.find(params[:id])
    # rescue
    #   @beacon = Beacon.find_by(:uuid => params[:id])
    #   @remote = true
    # end
  end

  # Setup for remote queries.
  def set_beacon_remote
    @beacon = Beacon.find_by(uuid: params[:uuid])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def beacon_params
    params.require(:beacon).permit(:uuid, :board_id)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:create]

  # GET /posts
  # GET /posts.json
  def index
    if params[:board_id] # if board_id specified by url parameter
      @posts = Post.select { |post| post.board_id.to_s == params[:board_id] }
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # POST /posts.json
  def remote
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        # format.json { redirect_to board_url(@post.board, format: :json) }
        format.json { render :remote, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content, :board_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beacons_helper.rb
module BeaconsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/beacons/_form.html.erb
<%= form_for(@beacon) do |f| %>
  <% if @beacon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beacon.errors.count, "error") %> prohibited this beacon from being saved:</h2>

      <ul>
      <% @beacon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <% @dummy_board = Board.new(:id => nil, :title => "") %>
  <div class="field">
    <%= f.label :board_id %><br>
    <%= f.collection_select :board_id,
     Board.all.unshift(@dummy_board), :id, :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beacons/edit.html.erb
<h1>Editing Beacon</h1>

<%= render 'form' %>

<%= link_to 'Show', @beacon %> |
<%= link_to 'Beacons', beacons_path %> |
<%= link_to 'Top', boards_path %>

app/views/beacons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beacons</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beacons.each do |beacon| %>
      <tr>
        <td><%= beacon.uuid %></td>
        <td>
          <% if beacon.board.nil? %>
            -
          <% else %>
            <%= link_to beacon.board.title, beacon.board %>
          <% end %>
        </td>
        <td><%= link_to 'Show', beacon %></td>
        <td><%= link_to 'Edit', edit_beacon_path(beacon) %></td>
        <td><%= link_to 'Destroy', beacon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beacon', new_beacon_path %> |
<%= link_to 'Top', boards_path %>

app/views/beacons/new.html.erb
<h1>New Beacon</h1>

<%= render 'form' %>

<%= link_to 'Beacons', beacons_path %> |
<%= link_to 'Top', boards_path %>

app/views/beacons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @beacon.uuid %>
</p>

<p>
  <strong>Board:</strong>
  <% if @beacon.board.nil? %>
    -
  <% else %>
    <%= link_to @beacon.board.title, @beacon.board %>
  <% end %>
</p>

<%= link_to 'Edit', edit_beacon_path(@beacon) %> |
<%= link_to 'Beacons', beacons_path %> |
<%= link_to 'Top', boards_path %>

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Top', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>koko</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= link_to board.title, board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %> |
<%= link_to 'Beacons', beacons_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Top', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Beacons:</strong>
  <% @board.beacons.each do |beacon| %>
    <%= link_to beacon.uuid, beacon %>
  <% end %>
  <br>
  <%= select_tag 'edit[beacon]',
    options_for_select(
      Beacon.where(board_id: [nil, @board.id])
            .map{ |beacon| [beacon.uuid, beacon.id] }) %>
  <button onclick =
    "location.href = '/beacons/' + document.getElementById('edit_beacon').value + '/edit'">
      Edit
  </button>
</p>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Content</th>
    </tr>
  </thead>
  <tbody>
    <% @board.posts.order(:created_at).each do |post| %>
      <tr>
        <td><%= post.created_at %></td>
        <td><%= post.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <strong>New Post</strong>
</p>
<% @post = Post.new %>
<% @post.board_id = @board.id %>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %>
         prohibited this post from being saved:
      </h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <%= f.hidden_field :board_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Top', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KokoServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :board_id %><br>
    <%= f.number_field :board_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<%= link_to 'Top', boards_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.board_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %> |
<%= link_to 'Top', boards_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %> |
<%= link_to 'Top', boards_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Board:</strong>
  <%= @post.board.title %>
</p>

<%= link_to 'Back', @post.board %> |
<%= link_to 'Top', boards_path %>